AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  Api:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./api
      Environment:
        Variables:
          DETECTORDAG_JWT_DURATION: "2h"
          DETECTORDAG_JWT_SECRET: "dummy-secret"
      Handler: main
      Runtime: go1.x
      Timeout: 5
      Events:
        Auth:
          Type: Api
          Properties:
            Path: /v1/auth
            Method: post
        AuthOptions:
          Type: Api
          Properties:
            Path: /v1/auth
            Method: options
        UpdateDevice:
          Type: Api
          Properties:
            Path: /v1/devices/{deviceId}
            Method: patch
        DeviceOptions:
          Type: Api
          Properties:
            Path: /v1/devices/{deviceId}
            Method: options
        GetAccount:
          Type: Api
          Properties:
            Path: /v1/accounts/{accountId}
            Method: get
        AccountOptions:
          Type: Api
          Properties:
            Path: /v1/accounts/{accountId}
            Method: options
        UpdateAccount:
          Type: Api
          Properties:
            Path: /v1/accounts/{accountId}
            Method: patch
        GetAccountDevices:
          Type: Api
          Properties:
            Path: /v1/accounts/{accountId}/devices
            Method: get
        AccountDevicesOptions:
          Type: Api
          Properties:
            Path: /v1/accounts/{accountId}/devices
            Method: options
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - 'dynamodb:GetItem'
                - 'dynamodb:UpdateItem'
                - 'dynamodb:Query'
              Resource:
                - !Sub "arn:${AWS::Partition}:dynamodb:${AWS::Region}:${AWS::AccountId}:table/accounts"
                - !Sub "arn:${AWS::Partition}:dynamodb:${AWS::Region}:${AWS::AccountId}:table/accounts/index/*"
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - 'iot:ListThings'
              Resource: '*'
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - 'iot:DescribeThing'
                - 'iot:ListThingGroupsForThing'
                - 'iot:GetThingShadow'
                - 'iot:UpdateThingShadow'
              Resource:
                - !Sub "arn:${AWS::Partition}:iot:${AWS::Region}:${AWS::AccountId}:thing/*"
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - 'iot:DescribeEndpoint'
              Resource: '*'
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - 'ses:VerifyEmailIdentity'
                - 'ses:GetIdentityVerificationAttributes'
              Resource: '*'
  PowerStatusChanged:
    Type: AWS::IoT::TopicRule
    Properties:
      TopicRulePayload:
        RuleDisabled: 'false'
        AwsIotSqlVersion: '2016-03-23'
        Sql: SELECT topic(3) as deviceId, timestamp, current.state.reported as state, current.metadata.reported as updated FROM '$aws/things/+/shadow/update/documents' WHERE current.state.reported.status <> previous.state.reported.status
        Actions:
        - Lambda:
            FunctionArn: !GetAtt consumer.Arn
  ConnectionStatusChanged:
    Type: AWS::IoT::TopicRule
    Properties:
      TopicRulePayload:
        RuleDisabled: 'false'
        Sql: SELECT * FROM '$aws/events/presence/#'
        AwsIotSqlVersion: '2016-03-23'
        Actions:
        - Lambda:
            FunctionArn: !GetAtt ConnectionStatusListener.Arn
  PowerUpdateIsConnected:
    Type: AWS::IoT::TopicRule
    Properties:
      TopicRulePayload:
        RuleDisabled: 'false'
        AwsIotSqlVersion: '2016-03-23'
        Sql: SELECT topic(3) as clientId, timestamp() as timestamp, "connected" as eventType FROM '$aws/things/+/shadow/update'
        Actions:
        - Lambda:
            FunctionArn: !GetAtt ConnectionStatusListener.Arn
  ConsumerPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt consumer.Arn
      Principal: iot.amazonaws.com
      SourceArn: !GetAtt PowerStatusChanged.Arn
  ConnectionStatusListenerPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt ConnectionStatusListener.Arn
      Principal: iot.amazonaws.com
      SourceArn: !GetAtt ConnectionStatusChanged.Arn
  PowerUpdateIsConnectedPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt ConnectionStatusListener.Arn
      Principal: iot.amazonaws.com
      SourceArn: !GetAtt PowerUpdateIsConnected.Arn
  consumer:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./consumer
      Environment:
        Variables:
          SENDER_EMAIL: detectordag@sambriggs.dev
      Handler: main
      Runtime: go1.x
      Policies:
        - DynamoDBReadPolicy:
            TableName: accounts
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - 'ses:SendEmail'
                - 'ses:SendRawEmail'
                - 'ses:GetIdentityVerificationAttributes'
              Resource: '*'
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - 'dynamodb:GetItem'
              Resource:
                - !Sub "arn:${AWS::Partition}:dynamodb:${AWS::Region}:${AWS::AccountId}:table/accounts"
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - 'iot:DescribeThing'
                - 'iot:GetThingShadow'
              Resource:
                - !Sub "arn:${AWS::Partition}:iot:${AWS::Region}:${AWS::AccountId}:thing/*"
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - 'iot:DescribeEndpoint'
              Resource: '*'
  ConnectionStatusQueue:
    Type: AWS::SQS::Queue
    Properties:
      DelaySeconds: 5
  ConnectionStatusQueueMap:
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      EventSourceArn: !GetAtt ConnectionStatusQueue.Arn
      FunctionName: !GetAtt Disconnected.Arn
  ConnectionStatusListener:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./connection/listener
      Environment:
        Variables:
          SENDER_EMAIL: detectordag@sambriggs.dev
          DELAY_QUEUE_URL: !Ref ConnectionStatusQueue
      Handler: main
      Runtime: go1.x
      Timeout: 5
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - 'ses:SendEmail'
                - 'ses:SendRawEmail'
                - 'ses:GetIdentityVerificationAttributes'
              Resource: '*'
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - 'iot:DescribeThing'
                - 'iot:GetThingShadow'
                - 'iot:UpdateThingShadow'
              Resource:
                - !Sub "arn:${AWS::Partition}:iot:${AWS::Region}:${AWS::AccountId}:thing/*"
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - 'iot:Publish'
              Resource:
                - !Sub "arn:${AWS::Partition}:iot:${AWS::Region}:${AWS::AccountId}:topic/dags/*/status/request"
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - 'iot:DescribeEndpoint'
              Resource: '*'
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - 'sqs:SendMessage'
              Resource: !Sub ${ConnectionStatusQueue.Arn}
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - 'dynamodb:GetItem'
              Resource:
                - !Sub "arn:${AWS::Partition}:dynamodb:${AWS::Region}:${AWS::AccountId}:table/accounts"
  Disconnected:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./connection/disconnected
      Environment:
        Variables:
          SENDER_EMAIL: detectordag@sambriggs.dev
      Handler: main
      Runtime: go1.x
      Timeout: 5
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - 'ses:SendEmail'
                - 'ses:SendRawEmail'
                - 'ses:GetIdentityVerificationAttributes'
              Resource: '*'
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - 'iot:DescribeThing'
                - 'iot:GetThingShadow'
                - 'iot:UpdateThingShadow'
              Resource:
                - !Sub "arn:${AWS::Partition}:iot:${AWS::Region}:${AWS::AccountId}:thing/*"
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - 'iot:DescribeEndpoint'
              Resource: '*'
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - 'dynamodb:GetItem'
              Resource:
                - !Sub "arn:${AWS::Partition}:dynamodb:${AWS::Region}:${AWS::AccountId}:table/accounts"
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - 'sqs:DeleteMessage'
                - 'sqs:GetQueueAttributes'
                - 'sqs:ReceiveMessage'
              Resource: !Sub ${ConnectionStatusQueue.Arn}
  ThingPolicy:
    Type: AWS::IoT::Policy
    Properties:
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action:
          - iot:Connect
          Resource:
          - arn:aws:iot:eu-west-2:670763423833:client/${iot:Connection.Thing.ThingName}
        - Effect: Allow
          Action:
          - iot:Publish
          Resource:
          - arn:aws:iot:eu-west-2:670763423833:topic/$aws/things/${iot:Connection.Thing.ThingName}/shadow/update
        - Effect: Allow
          Action:
          - iot:Subscribe
          Resource:
          - arn:aws:iot:eu-west-2:670763423833:topicfilter/$aws/things/${iot:Connection.Thing.ThingName}/shadow/update/*
          - arn:aws:iot:eu-west-2:670763423833:topicfilter/dags/${iot:Connection.Thing.ThingName}/status/request
        - Effect: Allow
          Action:
          - iot:Receive
          Resource:
          - arn:aws:iot:eu-west-2:670763423833:topic/$aws/things/${iot:Connection.Thing.ThingName}/shadow/update/*
          - arn:aws:iot:eu-west-2:670763423833:topic/dags/${iot:Connection.Thing.ThingName}/status/request

