AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  FrontendBucket:
    Type: AWS::S3::Bucket
    Properties:
      WebsiteConfiguration:
         IndexDocument: index.html
  FrontendBucketAllowPublicReadPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref FrontendBucket
      PolicyDocument:
        Id: FrontendBucketPolicy
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - "s3:GetObject"
            Resource: !Sub
              - "arn:${AWS::Partition}:s3:${AWS::Region}:${AWS::AccountId}:${BucketName}/*"
              - { BucketName: !Ref FrontendBucket}
            Principal: "*"
  Api:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./api
      Environment:
        Variables:
          DETECTORDAG_JWT_DURATION: "2h"
          DETECTORDAG_JWT_SECRET: "dummy-secret"
      Handler: api
      Runtime: go1.x
      Timeout: 5
      Events:
        Auth:
          Type: Api
          Properties:
            Path: /v1/auth
            Method: post
        AuthOptions:
          Type: Api
          Properties:
            Path: /v1/auth
            Method: options
        UpdateDevice:
          Type: Api
          Properties:
            Path: /v1/device/{deviceId}
            Method: patch
        DeviceOptions:
          Type: Api
          Properties:
            Path: /v1/device/{deviceId}
            Method: options
        GetAccount:
          Type: Api
          Properties:
            Path: /v1/accounts/{accountId}
            Method: get
        AccountOptions:
          Type: Api
          Properties:
            Path: /v1/accounts/{accountId}
            Method: options
        UpdateAccount:
          Type: Api
          Properties:
            Path: /v1/accounts/{accountId}
            Method: patch
        GetAccountDevices:
          Type: Api
          Properties:
            Path: /v1/accounts/{accountId}/devices
            Method: get
        AccountDevicesOptions:
          Type: Api
          Properties:
            Path: /v1/accounts/{accountId}/devices
            Method: options
        RegisterDevice:
          Type: Api
          Properties:
            Path: /v1/accounts/{accountId}/devices/{deviceId}
            Method: put
        RegisterDeviceOptions:
          Type: Api
          Properties:
            Path: /v1/accounts/{accountId}/devices/{deviceId}
            Method: options
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - 'dynamodb:GetItem'
                - 'dynamodb:UpdateItem'
                - 'dynamodb:Query'
              Resource:
                - !Sub "arn:${AWS::Partition}:dynamodb:${AWS::Region}:${AWS::AccountId}:table/accounts"
                - !Sub "arn:${AWS::Partition}:dynamodb:${AWS::Region}:${AWS::AccountId}:table/accounts/index/*"
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - 'iot:ListThings'
                - 'iot:CreateKeysAndCertificate'
                - 'iot:UpdateCertificate'
                - 'iot:DeleteCertificate'
                - 'iot:DescribeCertificate'
                - 'iot:DescribeThingType'
                - 'iot:DescribeThingGroup'
                - 'iot:RegisterThing'
                - 'iot:AddThingToThingGroup'
                - 'iot:AttachThingPrincipal'
              Resource: '*'
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - 'iot:DescribeThing'
                - 'iot:ListThingGroupsForThing'
                - 'iot:GetThingShadow'
                - 'iot:CreateThing'
              Resource:
                - !Sub "arn:${AWS::Partition}:iot:${AWS::Region}:${AWS::AccountId}:thing/*"
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - 'iot:DescribeEndpoint'
              Resource: '*'
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - 'ses:VerifyEmailIdentity'
                - 'ses:GetIdentityVerificationAttributes'
              Resource: '*'
  consumer:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./consumer
      Handler: consumer
      Runtime: go1.x
      Policies:
        - DynamoDBReadPolicy:
            TableName: accounts
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - 'ses:SendEmail'
                - 'ses:SendRawEmail'
              Resource: '*'
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - 'dynamodb:GetItem'
              Resource:
                - !Sub "arn:${AWS::Partition}:dynamodb:${AWS::Region}:${AWS::AccountId}:table/accounts"
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - 'iot:DescribeThing'
              Resource:
                - !Sub "arn:${AWS::Partition}:iot:${AWS::Region}:${AWS::AccountId}:thing/*"
  FindLost:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./visibility
      Handler: findlost
      Runtime: go1.x
      Timeout: 5
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - 'ses:SendEmail'
                - 'ses:SendRawEmail'
              Resource: '*'
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - 'iot:ListThings'
              Resource: '*'
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
              Action:
                - 'iot:DescribeThing'
                - 'iot:UpdateThing'
              Resource:
                - !Sub "arn:${AWS::Partition}:iot:${AWS::Region}:${AWS::AccountId}:thing/*"
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - 'iot:GetThingShadow'
              Resource:
                - !Sub "arn:${AWS::Partition}:iot:${AWS::Region}:${AWS::AccountId}:thing/*"
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - 'iot:DescribeEndpoint'
              Resource: '*'
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - 'dynamodb:GetItem'
              Resource:
                - !Sub "arn:${AWS::Partition}:dynamodb:${AWS::Region}:${AWS::AccountId}:table/accounts"
