AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  Api:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./api
      Environment:
        Variables:
          DETECTORDAG_JWT_DURATION: "2h"
          DETECTORDAG_JWT_SECRET: "dummy-secret"
      Handler: main
      Runtime: go1.x
      Timeout: 5
      Events:
        Auth:
          Type: Api
          Properties:
            Path: /v1/auth
            Method: post
        AuthOptions:
          Type: Api
          Properties:
            Path: /v1/auth
            Method: options
        UpdateDevice:
          Type: Api
          Properties:
            Path: /v1/device/{deviceId}
            Method: patch
        DeviceOptions:
          Type: Api
          Properties:
            Path: /v1/device/{deviceId}
            Method: options
        GetAccount:
          Type: Api
          Properties:
            Path: /v1/accounts/{accountId}
            Method: get
        AccountOptions:
          Type: Api
          Properties:
            Path: /v1/accounts/{accountId}
            Method: options
        UpdateAccount:
          Type: Api
          Properties:
            Path: /v1/accounts/{accountId}
            Method: patch
        GetAccountDevices:
          Type: Api
          Properties:
            Path: /v1/accounts/{accountId}/devices
            Method: get
        AccountDevicesOptions:
          Type: Api
          Properties:
            Path: /v1/accounts/{accountId}/devices
            Method: options
        RegisterDevice:
          Type: Api
          Properties:
            Path: /v1/accounts/{accountId}/devices/{deviceId}
            Method: put
        RegisterDeviceOptions:
          Type: Api
          Properties:
            Path: /v1/accounts/{accountId}/devices/{deviceId}
            Method: options
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - 'dynamodb:GetItem'
                - 'dynamodb:UpdateItem'
                - 'dynamodb:Query'
              Resource:
                - !Sub "arn:${AWS::Partition}:dynamodb:${AWS::Region}:${AWS::AccountId}:table/accounts"
                - !Sub "arn:${AWS::Partition}:dynamodb:${AWS::Region}:${AWS::AccountId}:table/accounts/index/*"
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - 'iot:ListThings'
                - 'iot:CreateKeysAndCertificate'
                - 'iot:UpdateCertificate'
                - 'iot:DeleteCertificate'
                - 'iot:DescribeCertificate'
                - 'iot:DescribeThingType'
                - 'iot:DescribeThingGroup'
                - 'iot:RegisterThing'
                - 'iot:AddThingToThingGroup'
                - 'iot:AttachThingPrincipal'
              Resource: '*'
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - 'iot:DescribeThing'
                - 'iot:ListThingGroupsForThing'
                - 'iot:GetThingShadow'
                - 'iot:CreateThing'
              Resource:
                - !Sub "arn:${AWS::Partition}:iot:${AWS::Region}:${AWS::AccountId}:thing/*"
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - 'iot:DescribeEndpoint'
              Resource: '*'
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - 'ses:VerifyEmailIdentity'
                - 'ses:GetIdentityVerificationAttributes'
              Resource: '*'
  consumer:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./consumer
      Environment:
        Variables:
          SENDER_EMAIL: detectordag@sambriggs.dev
      Handler: main
      Runtime: go1.x
      Policies:
        - DynamoDBReadPolicy:
            TableName: accounts
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - 'ses:SendEmail'
                - 'ses:SendRawEmail'
                - 'ses:GetIdentityVerificationAttributes'
              Resource: '*'
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - 'dynamodb:GetItem'
              Resource:
                - !Sub "arn:${AWS::Partition}:dynamodb:${AWS::Region}:${AWS::AccountId}:table/accounts"
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - 'iot:DescribeThing'
              Resource:
                - !Sub "arn:${AWS::Partition}:iot:${AWS::Region}:${AWS::AccountId}:thing/*"
  ConnectionStatusQueue:
    Type: AWS::SQS::Queue
    Properties:
      DelaySeconds: 5
  ConnectionStatusQueueMap:
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      EventSourceArn: !GetAtt ConnectionStatusQueue.Arn
      FunctionName: !GetAtt Disconnected.Arn
  ConnectionStatusListener:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./connection/listener
      Environment:
        Variables:
          SENDER_EMAIL: detectordag@sambriggs.dev
          DELAY_QUEUE_URL: !Ref ConnectionStatusQueue
      Handler: main
      Runtime: go1.x
      Timeout: 5
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - 'ses:SendEmail'
                - 'ses:SendRawEmail'
                - 'ses:GetIdentityVerificationAttributes'
              Resource: '*'
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
              Action:
                - 'iot:DescribeThing'
                - 'iot:GetThingShadow'
                - 'iot:UpdateThingShadow'
              Resource:
                - !Sub "arn:${AWS::Partition}:iot:${AWS::Region}:${AWS::AccountId}:thing/*"
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - 'iot:DescribeEndpoint'
              Resource: '*'
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - 'sqs:SendMessage'
              Resource: !Sub ${ConnectionStatusQueue.Arn}
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - 'dynamodb:GetItem'
              Resource:
                - !Sub "arn:${AWS::Partition}:dynamodb:${AWS::Region}:${AWS::AccountId}:table/accounts"
  Disconnected:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./connection/disconnected
      Environment:
        Variables:
          SENDER_EMAIL: detectordag@sambriggs.dev
      Handler: main
      Runtime: go1.x
      Timeout: 5
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - 'ses:SendEmail'
                - 'ses:SendRawEmail'
                - 'ses:GetIdentityVerificationAttributes'
              Resource: '*'
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
              Action:
                - 'iot:DescribeThing'
                - 'iot:GetThingShadow'
                - 'iot:UpdateThingShadow'
              Resource:
                - !Sub "arn:${AWS::Partition}:iot:${AWS::Region}:${AWS::AccountId}:thing/*"
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - 'iot:DescribeEndpoint'
              Resource: '*'
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - 'dynamodb:GetItem'
              Resource:
                - !Sub "arn:${AWS::Partition}:dynamodb:${AWS::Region}:${AWS::AccountId}:table/accounts"
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - 'sqs:DeleteMessage'
                - 'sqs:GetQueueAttributes'
                - 'sqs:ReceiveMessage'
              Resource: !Sub ${ConnectionStatusQueue.Arn}
