Transform: AWS::Serverless-2016-10-31
Resources:
  consumer:
    Type: AWS::Serverless::Function
    Properties:
      Handler: consumer
      Runtime: go1.x
      Policies:
        - DynamoDBCrudPolicy:
            TableName: devices
        - DynamoDBReadPolicy:
            TableName: accounts
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - 'ses:SendEmail'
                - 'ses:SendRawEmail'
              Resource: '*'
