/*
 * Detectordag
 *
 * API for detectordag JAMStack dashboard
 *
 * API version: 1.0.0
 * Contact: briggySmalls90@gmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/briggysmalls/detectordag/shared/database"
	"github.com/gorilla/mux"
	"github.com/kelseyhightower/envconfig"
)

type Route struct {
	Name        string
	Method      string
	Pattern     string
	HandlerFunc http.HandlerFunc
}

type handlerer struct {
	db     database.Client
	config Config
}

type Config struct {
	JwtSecret string `split_words:"true"`
}

type Routes []Route

func NewConfig() (*Config, error) {
	// Load config
	var c Config
	err := envconfig.Process("detectordag", &c)
	if err != nil {
		return nil, err
	}
	return &c, nil
}

func NewRouter(config *Config, db database.Client) *mux.Router {
	// Create the router
	router := mux.NewRouter().StrictSlash(true)
	// Create a handlerer
	h := handlerer{
		config: *config,
		db:     db,
	}
	// Prepare the routes
	var routes = Routes{
		Route{
			"Index",
			"GET",
			"/v1/",
			Index,
		},

		Route{
			"GetAccount",
			strings.ToUpper("Get"),
			"/v1/accounts/{accountId}",
			h.GetAccount,
		},

		Route{
			"GetDevices",
			strings.ToUpper("Get"),
			"/v1/accounts/{accountId}/devices",
			h.GetDevices,
		},

		Route{
			"UpdateAccount",
			strings.ToUpper("Patch"),
			"/v1/accounts/{accountId}",
			h.UpdateAccount,
		},

		Route{
			"Auth",
			strings.ToUpper("Post"),
			"/v1/auth",
			h.Auth,
		},

		Route{
			"UpdateDevice",
			strings.ToUpper("Patch"),
			"/v1/devices/{deviceId}",
			h.UpdateDevice,
		},
	}

	// Build the router
	for _, route := range routes {
		var handler http.Handler
		handler = route.HandlerFunc
		handler = Logger(handler, route.Name)

		router.
			Methods(route.Method).
			Path(route.Pattern).
			Name(route.Name).
			Handler(handler)
	}

	return router
}

func Index(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintf(w, "Hello World!")
}
