/*
 * Detectordag
 *
 * API for detectordag JAMStack dashboard
 *
 * API version: 1.0.0
 * Contact: briggySmalls90@gmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

import (
	"errors"
	"github.com/gorilla/mux"
	"net/http"
)

func (s *server) GetAccount(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json; charset=UTF-8")
	w.WriteHeader(http.StatusNotImplemented)
}

func (s *server) GetDevices(w http.ResponseWriter, r *http.Request) {
	// We return JSON no matter what
	w.Header().Set("Content-Type", "application/json; charset=UTF-8")
	// Pull out the account ID
	vars := mux.Vars(r)
	if _, ok := vars["articleId"]; !ok {
		setError(w, errors.New("Article ID not supplied in path"), http.StatusBadRequest)
		return
	}
	// Fetch the devices associated with the account
	_, err := s.db.GetDevicesByAccount(vars["articleId"])
	if err != nil {
		setError(w, err, http.StatusInternalServerError)
	}
	// Request each device's shadow
	w.WriteHeader(http.StatusOK)
}

func (s *server) UpdateAccount(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json; charset=UTF-8")
	w.WriteHeader(http.StatusNotImplemented)
}
