/*
 * Detectordag
 *
 * API for detectordag JAMStack dashboard
 *
 * API version: 1.0.0
 * Contact: briggySmalls90@gmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

import (
	"encoding/json"
	models "github.com/briggysmalls/detectordag/api/swagger/go"
	"net/http"
)

func (s *server) GetAccount(w http.ResponseWriter, r *http.Request) {
	// Validate the sender is authorised
	accountId := s.validateAccount(w, r)
	if accountId == nil {
		return
	}
	// Request the account
	account, err := s.db.GetAccountById(*accountId)
	if err != nil {
		setError(w, err, http.StatusInternalServerError)
		return
	}
	// Build the response
	payload := models.Account{
		Username: account.Username,
		Emails:   account.Emails,
	}
	// Prepare the JSON response
	body, err := json.Marshal(payload)
	if err != nil {
		setError(w, err, http.StatusInternalServerError)
	}
	// Write the response
	w.WriteHeader(http.StatusOK)
	w.Write(body)
}

func (s *server) GetDevices(w http.ResponseWriter, r *http.Request) {
	var err error
	// Validate the sender is authorised
	accountId := s.validateAccount(w, r)
	if accountId == nil {
		return
	}
	// Fetch the devices associated with the account
	devices, err := s.db.GetDevicesByAccount(*accountId)
	if err != nil {
		setError(w, err, http.StatusInternalServerError)
		return
	}
	// Request each device's shadow
	payload := make([]models.Device, len(devices))
	for i, device := range devices {
		// Request the shadow
		shdw, err := s.shadow.Get(device.DeviceId)
		if err != nil {
			setError(w, err, http.StatusInternalServerError)
			return
		}
		// Coerce the data into the right form
		status, ok := shdw.State.Reported["status"].(bool)
		if !ok {
			setError(w, err, http.StatusInternalServerError)
		}
		// Build the payload
		payload[i] = models.Device{
			Name:     device.Name,
			DeviceId: device.DeviceId,
			Updated:  shdw.Metadata.Reported["status"].Timestamp.Time,
			State:    &models.DeviceState{Power: status},
		}
	}
	// Prepare the JSON response
	body, err := json.Marshal(payload)
	if err != nil {
		setError(w, err, http.StatusInternalServerError)
	}
	// Write the response
	w.WriteHeader(http.StatusOK)
	w.Write(body)
}

func (s *server) UpdateAccount(w http.ResponseWriter, r *http.Request) {
	// Validate the sender is authorised
	accountId := s.validateAccount(w, r)
	if accountId == nil {
		return
	}
	// Parse the emails from the request
	var emails models.Emails
	var err error
	err = json.NewDecoder(r.Body).Decode(&emails)
	if err != nil {
		setError(w, err, http.StatusBadRequest)
		return
	}
	// Request that emails are verified

	// Update the database
	err = s.db.UpdateAccountEmails(*accountId, emails.Emails)
	if err != nil {
		setError(w, err, http.StatusInternalServerError)
		return
	}
	// Write the response
	w.WriteHeader(http.StatusOK)
}
