/*
 * Detectordag
 *
 * API for detectordag JAMStack dashboard
 *
 * API version: 1.0.0
 * Contact: briggySmalls90@gmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

import (
	"encoding/json"
	models "github.com/briggysmalls/detectordag/api/swagger/go"
	"golang.org/x/crypto/bcrypt"
	"net/http"
)

const (
	expiryDuration = 1500
	issuer         = "detectordag"
)

func (s *server) Auth(w http.ResponseWriter, r *http.Request) {
	// Whatever happens, we return JSON
	w.Header().Set("Content-Type", "application/json; charset=UTF-8")
	// Try to parse the body
	var creds models.Credentials
	var err error
	err = json.NewDecoder(r.Body).Decode(&creds)
	if err != nil {
		setError(w, err, http.StatusBadRequest)
		return
	}
	// Query for an account with the given username
	account, err := s.db.GetAccountByUsername(creds.Username)
	if err != nil {
		setError(w, err, http.StatusForbidden)
		return
	}
	// Check that the password is correct
	err = bcrypt.CompareHashAndPassword([]byte(account.Password), []byte(creds.Password))
	if err != nil {
		setError(w, err, http.StatusForbidden)
		return
	}
	// Create a token for the authenticated user
	token, err := s.createToken(account.AccountId)
	if err != nil {
		setError(w, err, http.StatusInternalServerError)
	}
	// Build response content
	content := models.Token{
		AccountId: account.AccountId,
		Token:     token,
	}
	body, err := json.Marshal(content)
	if err != nil {
		setError(w, err, http.StatusInternalServerError)
	}
	// Write the response
	w.WriteHeader(http.StatusOK)
	w.Write(body)
}

func setError(w http.ResponseWriter, err error, status int) {
	// TODO: If 5xx error then hide message unless in debug
	// Create the error struct
	m := models.ModelError{
		Error_: err.Error(),
	}
	// Marshal into string
	content, err := json.Marshal(m)
	if err != nil {
		// What do ew
		http.Error(w, "{\"error\": \"Failed to format error message\"}", http.StatusInternalServerError)
		return
	}
	// Write the output
	http.Error(w, string(content), status)
}

func raiseError(w http.ResponseWriter, err error, status int) {
	if err != nil {
		http.Error(w, err.Error(), status)
	}
}
