/*
 * Detectordag
 *
 * API for detectordag JAMStack dashboard
 *
 * API version: 1.0.0
 * Contact: briggySmalls90@gmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/briggysmalls/detectordag/shared/database"
	"github.com/gorilla/mux"
)

const (
	uuidRegex = `[0-9a-fA-F]{8}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{12}`
)

type Route struct {
	Name        string
	Method      string
	Pattern     string
	HandlerFunc http.HandlerFunc
}

type Routes []Route

func NewRouter(config *Config, db database.Client) *mux.Router {
	// Create the router
	router := mux.NewRouter().StrictSlash(true)
	// Create a handlerer
	h := server{
		config: *config,
		db:     db,
	}
	// Prepare the routes
	var routes = Routes{
		Route{
			"Index",
			"GET",
			"/v1/",
			Index,
		},

		Route{
			"GetAccount",
			strings.ToUpper("Get"),
			fmt.Sprintf("/v1/accounts/{accountId:%s}", uuidRegex),
			h.GetAccount,
		},

		Route{
			"GetDevices",
			strings.ToUpper("Get"),
			fmt.Sprintf("/v1/accounts/{accountId:%s}/devices", uuidRegex),
			h.GetDevices,
		},

		Route{
			"UpdateAccount",
			strings.ToUpper("Patch"),
			fmt.Sprintf("/v1/accounts/{accountId:%s}", uuidRegex),
			h.UpdateAccount,
		},

		Route{
			"Auth",
			strings.ToUpper("Post"),
			"/v1/auth",
			h.Auth,
		},

		Route{
			"UpdateDevice",
			strings.ToUpper("Patch"),
			"/v1/devices/{deviceId}",
			h.UpdateDevice,
		},
	}

	// Build the router
	for _, route := range routes {
		var handler http.Handler
		handler = route.HandlerFunc

		router.
			Methods(route.Method).
			Path(route.Pattern).
			Name(route.Name).
			Handler(handler)
	}

	return router
}

func Index(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintf(w, "Hello World!")
}
