AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  NotifyMissingDevices:
    Type: AWS::Serverless::Function
    Properties:
      Environment:
        Variables:
          DETECTORDAG_JWT_DURATION: "2h"
          DETECTORDAG_JWT_SECRET: "dummy-secret"
      Handler: api
      Runtime: go1.x
      Timeout: 5
      Events:
        CheckWebsiteScheduledEvent:
          Type: Schedule
          Properties:
            Schedule: rate(1 day)
