/*
 * Detectordag
 *
 * API for detectordag JAMStack dashboard
 *
 * API version: 1.0.0
 * Contact: briggySmalls90@gmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package server

import (
	"encoding/json"
	models "github.com/briggysmalls/detectordag/api/swagger/go"
	"golang.org/x/crypto/bcrypt"
	"net/http"
)

func (s *server) Auth(w http.ResponseWriter, r *http.Request) {
	// Try to parse the body
	var creds models.Credentials
	var err error
	err = json.NewDecoder(r.Body).Decode(&creds)
	if err != nil {
		setError(w, err, http.StatusBadRequest)
		return
	}
	// Query for an account with the given username
	account, err := s.db.GetAccountByUsername(creds.Username)
	if err != nil {
		setError(w, err, http.StatusForbidden)
		return
	}
	// Check that the password is correct
	err = bcrypt.CompareHashAndPassword([]byte(account.Password), []byte(creds.Password))
	if err != nil {
		setError(w, err, http.StatusForbidden)
		return
	}
	// Create a token for the authenticated user
	token, err := s.tokens.Create(account.AccountId)
	if err != nil {
		setError(w, err, http.StatusInternalServerError)
	}
	// Build response content
	content := models.Token{
		AccountId: account.AccountId,
		Token:     token,
	}
	body, err := json.Marshal(content)
	if err != nil {
		setError(w, err, http.StatusInternalServerError)
	}
	// Write the response
	w.WriteHeader(http.StatusOK)
	w.Write(body)
}
