# Next we begin the real image, first installing requirements
FROM balenalib/%%BALENA_MACHINE_NAME%%-node:13-run
# Set the working directory
WORKDIR /app
# Copy the dependencies first
COPY package.json package.json
COPY yarn.lock yarn.lock
# Ensure build-time variables are present
ARG CERTS_DIR
# Install dependencies
RUN yarn install
# Copy the rest of the package source
COPY . .
# Build the app
RUN yarn build
# Run the server
CMD ["yarn", "start", "-p", "80"]
