# Next we begin the real image, first installing requirements
FROM balenalib/%%BALENA_MACHINE_NAME%%-node:14-build
# Set the working directory
WORKDIR /app
# Copy the package source
COPY . .
# Install dependencies
RUN yarn install
# Build the app
RUN yarn build
# Run the server
CMD ["yarn", "start"]
