# Next we begin the real image, first installing requirements
FROM balenalib/%%BALENA_MACHINE_NAME%%-alpine-python:3.7
# Copy the package source
COPY . /app
WORKDIR /app
# Install package
RUN pip install .
# Set default command
CMD ["edge", "app"]
