AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  Api:
    Type: AWS::Serverless::Function
    Properties:
      Environment:
        Variables:
          DETECTORDAG_JWT_DURATION: "2h"
          DETECTORDAG_JWT_SECRET: "dummy-secret"
      Handler: api
      Runtime: go1.x
      Events:
        Auth:
          Type: Api
          Properties:
            Path: /v1/auth
            Method: post
        UpdateDevice:
          Type: Api
          Properties:
            Path: /v1/device/{deviceId}
            Method: patch
        GetAccount:
          Type: Api
          Properties:
            Path: /v1/accounts/{accountId}
            Method: get
        UpdateAccount:
          Type: Api
          Properties:
            Path: /v1/accounts/{accountId}
            Method: patch
        GetAccountDevices:
          Type: Api
          Properties:
            Path: /v1/accounts/{accountId}/devices
            Method: get
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - 'dynamodb:GetItem'
                - 'dynamodb:UpdateItem'
                - 'dynamodb:Query'
              Resource:
                - !Sub "arn:${AWS::Partition}:dynamodb:${AWS::Region}:${AWS::AccountId}:table/devices"
                - !Sub "arn:${AWS::Partition}:dynamodb:${AWS::Region}:${AWS::AccountId}:table/devices/index/*"
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - 'dynamodb:GetItem'
                - 'dynamodb:UpdateItem'
              Resource:
                - !Sub "arn:${AWS::Partition}:dynamodb:${AWS::Region}:${AWS::AccountId}:table/accounts"
                - !Sub "arn:${AWS::Partition}:dynamodb:${AWS::Region}:${AWS::AccountId}:table/accounts/index/*"
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - 'iot:GetThingShadow'
              Resource:
                - !Sub "arn:${AWS::Partition}:iot:${AWS::Region}:${AWS::AccountId}:thing/*"
